### ISSUE TITLE
Fix Nightmare Halls of Pain soft-lock

### ISSUE THREAD

**Issue by epyon** [chaosforgeorg/doomrl#168]
Ressurected enemies in locked areas can lock progress.

**Comment by OmegaTyrant** [comment]
This issue was fixed previously by disabling respawning in House Of Pain, but now that special levels no longer require having all respawns dead too to clear them, House Of Pain should no longer softlock you from enemies respawning in the locked rooms and thus it should be ok to re-enable N!/AoD respawning here again (there's the possibility that House Of Pain could have the current Hell's Arena bug of respawns still counting for clearing, but that's a bug that can be fixed alongside Hell's Arena).
