### ISSUE TITLE
Port to SDL2

### ISSUE THREAD

**Issue by epyon** [chaosforgeorg/doomrl#28]
- [x] needs new vsdl2 headers - possibly filtered for only what we'll need
- [x] will need help with the OSX version - possibly OpenGL upgrade is also needed
- [x] also needed SDL2 image and mixer - or do fmod on Linux also?

**Comment by rumly111** [comment]
I did port it to SDL2, but there are a lot of dirty hacks there :) Mostly because I didn't want to write additional code, so I simulated SDL1-ish behavior with SDL2 function calls. See the commits in my fork of fpcvalkyre.

I was porting DRL to Android, but in the end it worked only on my old tablet, and for newer versions of Android there were some issues. I never managed to fix that.

Anyway, the SDL2 port worked on my computer, but I didn't bother to organize my commits to make a proper PR. Tell me your thoughts.
