### ISSUE TITLE
How to make the GNU/Linux binary?

### ISSUE THREAD

**Issue by mdtrooper** [chaosforgeorg/doomrl#3]
I have been trying with:
```
$ fpcmake
Processing Makefile.fpc
 x86_64-linux requires: 
 Writing Makefile
$ make
Makefile:197: *** The Makefile doesn't support target x86_64-all, please run fpcmake first.  Stop.
```

And with:

```
$ bash mk_unix_dist.sh 666 linux ""
cp: cannot stat ‘../bin/musicmp3.lua’: No such file or directory
cp: cannot stat ‘../bin/musiccdmp3.lua’: No such file or directory
```

But it is not.

**Comment by mdeguzis** [comment]
I've been hunting this down as well. Backporting a few package to SteamOS so I can make full use of fpc/lazarus.

**Comment by subtract1** [comment]
I was unable to build on Linux.  I can build on Windows. But I can still help you past this bit.

You're missing the regular DoomRL resources--sounds and music.  Those aren't on this repository; you'll need to grab an actual copy of DoomRL and move the resources over.
You can build the engine without them but it won't get far.

**Comment by CyberKiller40** [comment]
Hi

I helped with Linux builds for AliensRL and DiabloRL in the past, these games use more or less the same engine and you'll find my notes on building for Linux on the command line (without the Lazarus IDE) in their docs. Hopefully this will give you something to start here with DRL.

Note: for DRL you'll want to convert the music (and sounds) to vorbis and modify the config files accordingly - mp3 support in SDL is usually nonexistent on GNU/Linux.

**Comment by mdeguzis** [comment]
hmm sounds like fun :) I'll see if I can hack away at this on the weekend. Thank you @CyberKiller40 . I assume you mean the GitHub repositories for those projects. avconv of ffmpeg can handle the ogg conversion fine I believe (as a separate step of course). I hope to get a native build for SteamOS/Ubuntu up next week possibly. Backporting Lazarus to SteamOS (yes I know it's mainly Jessie, but I prefer a proper backport) is giving me a headache. If it continues long enough I'll just snag the jessie-backports binaries.

**Comment by CyberKiller40** [comment]
I'm not sure if they're on github, last time they were on sourceforge, or somewhere else. But the Linux notes were AFAIR included with the binaries so you'll get them with the official downloads. And like I said - you don't need Lazarus, only the freepascal compiler which should be in your distro's repos.

As for audio conversion - ffmpeg handles it fine, but if you get a resulting ogg with vorbis+theora inside, then the game will crash. Only ogg with just vorbis is working so you need to add a switch to ffmpeg to drop the video part (-vn). You can use my script for this: http://paste.opensuse.org/88656780

**Comment by mdeguzis** [comment]
Thanks!

**Comment by mdeguzis** [comment]
Unfortunately I get the same error as OP regarding x86-64-all.

Steps to reproduce:

```
git clone https://github.com/ChaosForge/doomrl
cd doomrl
git clone https://github.com/ChaosForge/fpcvalkyrie
FPCDIR=/usr/lib/fpc/2.6.4/ fpcmake
make
```

**Comment by epyon** [comment]
I never built using makefiles. Building for Linux was done using the makefile.lua (custom build script). AFAIR, you have to have lua in path (possibly 5.1), and run "lua makefile.lua lq" or "./makefile.lua lq" - lq can be substituted for hq or all.

**Comment by mdeguzis** [comment]
Ok this gets farther. I'll try the lua approach.

```
apt-get install build-essential fpc lua5.1 liblua5.1-0-dev
git clone https://github.com/ChaosForge/doomrl
cd doomrl
git clone https://github.com/ChaosForge/fpcvalkyrie
FPCDIR=/usr/lib/fpc/2.6.4/ fpcmake -r
make
```

Output for fpc attempt: http://sprunge.us/ObKY

**Comment by epyon** [comment]
I'm pretty sure you need FPC 3.0.0 for the current sources.

**Comment by mdeguzis** [comment]
Well.. I just happened to backport 3.0.0 to my SteamOS repo :) But it didn't make a difference. I'll try with a fresh clone.

```
FPCDIR=/usr/lib/fpc/3.0.0/ fpcmake -r
OS_TARGET=linux make
```

**Comment by subtract1** [comment]
I'm rooting for you md.  Right now I have to test things through Wine...

I ran through lazarus directly on Mint.  There were no x86 binaries in the repo and I got stuck on an 'internal error' so I'm stuck waiting for someone else to figure it out.

**Comment by mdeguzis** [comment]
Ok, installed a crapton of fp-units packages after trying some of the easy to spot units packages,m but having no luck I used the verbose options of fpc to dig into the one pascal file unit failure.

`fpc -vut src/doomrl.pas`: [log file](http://sprunge.us/faUT)

As you can see, tons of the units I installed are found, but not vpkg or vsystems. Still checking out this path of reasoning here.

```
Searching file src/doomrl.pas... found
(DOOMRL)   Registering new unit SYSUTILS
(DOOMRL)   Registering new unit VSYSTEMS
(DOOMRL)   Registering new unit VDEBUG
(DOOMRL)   Registering new unit DOOMBASE
(DOOMRL)   Registering new unit DFOUTPUT
(DOOMRL)   Registering new unit VLOG
(DOOMRL)   Registering new unit VUTIL
(DOOMRL)   Registering new unit VOS
(DOOMRL)   Registering new unit DFDATA
(DOOMRL)   Registering new unit DOOMMODULE
(DOOMRL)   Registering new unit DOOMNET
(DOOMRL)   Registering new unit DOOMIO
(DOOMRL)   Load from DOOMRL (implementation) unit SYSUTILS
```

Since some units, such as rtl are found just fine, and the fact I could not find vpkg/vsystems anyway via `locate`, I think there is just some missing piece of the puzzle or a package is missing entirely to provide these two units.

**Comment by epyon** [comment]
Did you use makefile.lua as suggested? It runs fpc with the proper paths.

**Comment by mdeguzis** [comment]
I was just about to write that lol. `lua makefile.lua lq` would not pick up LINUX as the OS. Is there a verbose output for lua? I didn't see it in the man page.

**Comment by mdeguzis** [comment]
I tried `OS=LINUX lua makefile.lua lq` as well. That results in this: 

```
Free Pascal Compiler version 3.0.0+dfsg-9~bsos+1 [2016/12/08] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
vutil.pas(798,1) Error: Can't create object file: tmp/vutil.o (error code: 2)
vutil.pas(798,1) Fatal: Can't create object tmp/vutil.o
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Autodetected OS - LINUX
```

**Comment by epyon** [comment]
did you copy config-linux.lua to config.lua and change the VALKYRIE_ROOT to your Valkyrie path? Also, might be problem of write'ability - create a tmp folder in doomrl root (ergo bin, tmp and src)

**Comment by mdeguzis** [comment]
I'll keep a WIP local build script [here](https://github.com/mdeguzis/LibreGeek-Packaging/blob/steamos/doomrl/build-local.sh) that you can reference as I test this.

**Comment by mdeguzis** [comment]
WIP build script is pretty much there with the last suggestion you gave me. I cat the 2 line config to the config.lua file in the script. Verifed it displays in the same syntax as `config-linux.lua`.

**Comment by epyon** [comment]
bin/config.lua is the game configuation, config.lua is the build configuration.

**Comment by mdeguzis** [comment]
Same thing: http://sprunge.us/IaMS. I put a ending slash on the valkyrie root, otherwise the lua makefile would not be found for valkyrie.  I appreciate the help, as I'm sure you have better things to do :)

**Comment by simon-v** [comment]
I would like to point out, for all that's worth, that there is no need to convert any of the special level tracks to ogg, as they are already available in that format, and are freely downloadable from the music author's website. The same applies to Sonic Clang's tracks, which are redistributed in that very format with the Classic Doom 3 mod.

Why the game never packaged those instead is beyond my understanding.

**Comment by mdeguzis** [comment]
@simon-v , would you mind linking me those tracks, despite current issues building?

**Comment by simon-v** [comment]
The special level tracks are at http://simonvolpert.com/music/drla/ — the complete zip is in the bottom of the track listing.
The normal level tracks are obtainable from http://www.moddb.com/mods/classic-doom-3/downloads/classic-doom-3-131 (the files themselves are in `./sound/music/` inside `cdoom_sounds.pk4`, which is in `./cdoom` inside the `classic_doom_3_1.3.1.zip` archive). I might consider repacking and hosting just those files, if there is sufficient interest; From what i know, i don't think Sonic Clang will mind this any.

**Comment by tung** [comment]
I'm on Ubuntu 16.04 64-bit and, after running into the same issues as the folks above, I've managed to successfully compile DoomRL.

The error that says `Fatal: Internal error 2012090607` happens with Free Pascal Compiler version 3.0.0, which is unfortunately the version that Ubuntu 16.04 ships with. I worked around it by manually compiling 3.0.1 from source (which has a fix for that bug: http://bugs.freepascal.org/view.php?id=27580) and using that instead for compiling.

Rough list of steps:

1. Install fpc 3.0.0 from the standard packages.
2. Download fpcbuild.zip (80 MB) under "Download Daily Source Snapshot of the Fixes Tree" at http://www.freepascal.org/develop.var
3. Extract fpcbuild.zip (400 MB uncompressed).
4. Build fpc 3.0.1 using its `makepack` script (takes another 400 MB of room). I had to `touch doc-pdf.tar.gz` and pass in `CHECKLIBGDB=no` before it worked.
5. Install fpc 3.0.1 somewhere convenient (~200 MB once installed). I deleted all the fpcbuild stuff once it was done to free up the ~800 MB it was taking.
6. Clone doomrl repo.
7. Fill in the `doomrl/bin/{mp3,music,wav,wavhq}` directories with the binary assets from the standard DoomRL releases.
8. Clone fpcvalkyrie repo into a directory adjacent to doomrl.
9. Edit `fpcvalkyrie/scripts/lua_make.lua` to replace the standard fpc path with the 3.0.1 version, and stub out the logic in `make.svnrevision()` with a bogus return value since this is a git clone and not a subversion clone.
10. I had to edit `fpcvalkyrie/src/vtextio.pas` and comment out `{$IFDEF UNIX}Shell('reset'){$ENDIF}` because the compiler wasn't recognizing it for some reason.
11. Return to the `doomrl` directory and `mkdir tmp`.
12. Run `lua makefile.lua lq` in the `doomrl` directory.

If everything went right, you'll have something like `doomrl-linux-0998-beta1-lq.tar.gz` sitting in your `doomrl` directory, as well as a playable build of the game in the `doomrl/bin` directory.

If Ubuntu ever decides to package fpc 3.0.1 instead of 3.0.0, all of the custom fpc building and tweaking can just be skipped.

**Comment by mdeguzis** [comment]
Nice! I'll make up a Debian/SteamOS/Ubuntu package if things work well tomorrow or later tonight. I have some Hadoop things I need to get to today. Thank you very much for confirming a new `fpc` worked. I was about to try that as well. I have all the build steps already lined p, same as you do, just needed to get over the compiler error.  I will upload a 3.0.1 or higher `fpc` to my PPA as well. Just keep an eye on it.

https://launchpad.net/~mdeguzis/+archive/ubuntu/freepascal

Once confirmed working, i'll put up the game in the games PPA.

**Comment by mdeguzis** [comment]
There are a ton of Debian patches for fpc. When I have time I will backport them. In looking through their patches I saw which file the true version is pulled from, so I source the major.minor.patch version from that. Currently it is 3.1.1. There is no rush on this of course, but for Debian folk, I will provide a backported package at some point. I host non-Ubuntu at packages.libregeek.org.

**Comment by mdeguzis** [comment]
I tried using fpc-svn (which is at 3.1.1.r35149) with no luck. Below is the AUR package I started. Open the PKBUILD to see the WIP steps.

```
==> Starting build()...
Autodetected OS - LINUX
Free Pascal Compiler version 3.1.1 [2016/12/17] for x86_64
Copyright (c) 1993-2016 by Florian Klaempfl and others
doomrl.inc(11,4) Error: Illegal optimization specified "ASMCSE"
valkyrie.inc(12,4) Error: Illegal optimization specified "ASMCSE"
valkyrie.inc(12,4) Error: Illegal optimization specified "ASMCSE"
valkyrie.inc(12,4) Error: Illegal optimization specified "ASMCSE"
vutil.pas(283,1) Fatal: There were 4 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

* Log: http://sprunge.us/MLPI
* AUR Package: https://aur.archlinux.org/packages/doomrl-git

**Comment by mdeguzis** [comment]
Specifying `{ASMCSE OFF}` in the two inc files for doomrl/fpcvalkyrie got me farther.  This line seems to be for optimizing the assembler code. 

>ASMCSE "Use common subexpression elimination at the assembler level"

Log: http://slexy.org/view/s20gzxLBkS

**Comment by mdeguzis** [comment]
The only way I could get the linking to work is to dump in the static lib from https://sourceforge.net/projects/luabinaries/files/. But that doesn't seem quite like what should be the solution.

**Comment by mdeguzis** [comment]
Ok, everything compiles with the patches in the AUR build, but I need to figure out how to generate the wad ... the [snapshot script](https://github.com/ChaosForge/doomrl/blob/master/scripts/doomrl_snapshot.sh) notes running makewad in the bin/ folder, but I do not see that

**Comment by subtract1** [comment]
If you run in godmode you don't need the wads as it reads the scripts directly (well, you do NEED them but it doesn't use them).  Don't know if that helps you any but there you go.

**Comment by mdeguzis** [comment]
I was able to just get past that by temporarily symlinking the lib to the current directory where makewad is. I have a bit of testing to do. Everything builds and I modeled the pkgdir after the Linux tarball that is pushed out, but i'm sure I'll need to make some adjustments.

**Comment by mdeguzis** [comment]
fixed it :)

**Comment by mdeguzis** [comment]
Got everything to compile, wads etc, but get a run time error bout the Range :\ I can post the error later.

**Comment by subtract1** [comment]
I sincerely hope we get a good linux maintainer who can make DoomRL work and be all multiuser friendly.  I know that person won't be me so good luck.  We're all counting on you.

**Comment by mdtrooper** [comment]
@subtract1 Maybe we must to start a bounty software about the DoomRL in GNU/Linux.

**Comment by subtract1** [comment]
I think the main issue is we're all C gurus and not pascal gurus :/

**Comment by mdeguzis** [comment]
I've built plenty of programs (see my libregeek-packaging repo), this is my first that is pascal. I believe with a little nudge/bit of help I can get this. Usually, on a common build system, or something common (make/cmake/qmake etc.), you'll know where the issue lies. In this, you do need some inside knowledge here from the devs. We'll just have to wait until after they get the Jupiter Hell business in order. Just a matter of time. I can get the entire project to build with static/dynamic, but I must be missing something. I double checked my produced/packaged files vs. what is distributed via the tarball on the website.

Anyway, Happy Holidays (soon) everyone!

**Comment by subtract1** [comment]
Wait, you're trying to get an exact binary match?  I can guarantee you the source code that was GPLd is not the code that was used to build 0997; it's more like an alpha 0998 and a few things in the engine have changed (enough to require altered lua scripts)

**Comment by mdtrooper** [comment]
Well...Did somebody compile the DoomRL?

**Comment by mdtrooper** [comment]
With the recipe (https://github.com/ChaosForge/doomrl/issues/3#issuecomment-266179749) of @tung is easy more or less to make a binary of doomrl.

But in Debian, you must use the lua5.1 instead the 5.3 for to avoid this bug:
```
Timestamp   : 24-10-17 02:32:24
Error level : FATAL EXCEPTION
Message     : Fatal exception encountered

An unhandled exception occurred at $000000000052CB84 :
ELuaException : LuaError: DoomRL.OnLoadBase -- Field maxrange not found!
  $000000000052CB84 line 441 of src/doomlua.pas
  $00000000004D0AD0 line 1511 of ../fpcvalkyrie/src/vluasystem.pas
  $0000000000451F27 line 85 of src/doombase.pas

```
